// Generated by CoffeeScript 1.3.3
(function() {
  var app, server;

  global.express = require('express');

  global.http = require('http');

  global.app = app = express();

  server = http.createServer(app);

  require("" + __dirname + "/src/configuration");

  require("" + __dirname + "/src/controllers/home_controller");

  server.listen(3000);

  console.log("Server started on %d port in %s mode...", server.address().port, app.settings.env);

}).call(this);
